---
  name: Deployment of App
  on:
    push:
      branches: [ main ]
  jobs:
    build-and-deploy:
      name: Build and Deploy
      runs-on: ubuntu-latest
  
      steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: npm install
  
      - name: Test
        run: npm run test

      - name: Clear npm cache
        run: npm cache clean --force
        
      - name: Deploy
        run: |
          git config --global user.name 'gopesh-code'
          git config --global user.email 'gopeshkumarpathak@gmail.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}    
          npm run deploy